### ISSUE TITLE
No playstate.hx

### ISSUE THREAD

**Issue by MasterOak** [LilDrippyMyFnf/FNF-BitEnigne#13]
## why to add

**it mostly controls the entire engine**

If you want,ask me or @StefanBETA2008 for help

**Comment by LilDrippyMyFnf** [comment]
i suck i coding haxe,so sorry

also,this engine is not forked or made from psych engine,but still, ima add it

**Comment by MasterOak** [comment]
OK,but pls try your best to make the play state.hx and try not to copy `shadowmarios psych engine play state.hx`

**Comment by LilDrippyMyFnf** [comment]
ok i won't

**Comment by LilDrippyMyFnf** [comment]
@StefanBETA2008,do you know how to code haxe?

**Comment by LilDrippyMyFnf** [comment]
\
