### ISSUE TITLE
.Exe file

### ISSUE THREAD

**Issue by LilDrippyMyFnf** [LilDrippyMyFnf/FNF-BitEnigne#16]
can anyone modify the .exe file? cuz im on chromebook and i can't run exe files

**Comment by MemeHoovy** [comment]
> can anyone modify the .exe file? cuz im on chromebook and i can't run exe files

sure

**Comment by LilDrippyMyFnf** [comment]
ok

**Comment by MemeHoovy** [comment]
> ok

wait nvm you got it

**Comment by LilDrippyMyFnf** [comment]
ye
