### ISSUE TITLE
Lua,and PlayState files

### ISSUE THREAD

**Issue by LilDrippyMyFnf** [LilDrippyMyFnf/FNF-BitEnigne#18]
## Question 1

can anyone code playstate.hx? I'm bad at haxe so 😭 

## Question 2

should we add lua files? example: `healthdrain.lua,shaders.lua and more`

use '1' as question 1 and '2' as question 2

**Comment by MemeHoovy** [comment]
I'm playing d&b 3.0 rn

**Comment by LilDrippyMyFnf** [comment]
ok

**Comment by LilDrippyMyFnf** [comment]
https://scratch.mit.edu/projects/739649272/

**Comment by MemeHoovy** [comment]
> https://scratch.mit.edu/projects/739649272/

nice, but I can't access my scratch account, and I haven't used it in a couple years

**Comment by LilDrippyMyFnf** [comment]
oh ok

**Comment by MemeHoovy** [comment]
I'm back

**Comment by LilDrippyMyFnf** [comment]
ok

**Comment by MemeHoovy** [comment]
> ok

playstate file is added, as for the lua thing, you decide as to whether we should add it or not

**Comment by StefanBETA2008** [comment]
Nice Dude

**Comment by LilDrippyMyFnf** [comment]
thank you both for helping me ;)

**Comment by MemeHoovy** [comment]
> thank you both for helping me ;)

your welcome

**Comment by StefanBETA2008** [comment]
> thank you both for helping me ;)

No Problem

**Comment by LilDrippyMyFnf** [comment]
https://scratch.mit.edu/projects/660123834/

**Comment by MemeHoovy** [comment]
> https://scratch.mit.edu/projects/660123834/

is that the 2.5 version of welcome?

**Comment by LilDrippyMyFnf** [comment]
no,old welcome

**Comment by LilDrippyMyFnf** [comment]
i like to key its in

**Comment by MemeHoovy** [comment]
> i like to key its in

oh
