### ISSUE TITLE
The EXE Solution

### ISSUE THREAD

**Issue by StefanBETA2008** [LilDrippyMyFnf/FNF-BitEnigne#19]
If You Want To .EXE Program, You Need To Make Workflow File. So, Make Sure Do You Have Perfect All Code's And State For The Compile.

**Comment by StefanBETA2008** [comment]
Let Me Explain:
You Need To Add: `Project.xml` To Program.

**Comment by MemeHoovy** [comment]
more then that

**Comment by StefanBETA2008** [comment]
> more then that

And States + Substates To Work. I Will Help

**Comment by MemeHoovy** [comment]
> > more then that
> 
> And States + Substates To Work. I Will Help

cool

**Comment by StefanBETA2008** [comment]
I Will Use Some From PE And The Original

**Comment by MemeHoovy** [comment]
> I Will Use Some From PE And The Original

coolio

**Comment by MemeHoovy** [comment]
> I Will Use Some From PE And The Original

your discord don't work

**Comment by LilDrippyMyFnf** [comment]
you guys are a massive help ( im not using you guys as slaves ) but im bad at coding

**Comment by MemeHoovy** [comment]
> you guys are a massive help ( im not using you guys as slaves ) but im bad at coding

your welcome

**Comment by LilDrippyMyFnf** [comment]
:))))

**Comment by StefanBETA2008** [comment]
> > I Will Use Some From PE And The Original
> 
> your discord don't work

My Discord?

**Comment by MemeHoovy** [comment]
> > > I Will Use Some From PE And The Original
> > 
> > 
> > your discord don't work
> 
> My Discord?

ye, the username don't work

**Comment by StefanBETA2008** [comment]
> > > > I Will Use Some From PE And The Original
> > > 
> > > 
> > > your discord don't work
> > 
> > 
> > My Discord?
> 
> ye, the username don't work

Oh. I Just Changed The My Username

**Comment by LilDrippyMyFnf** [comment]
discord names?

**Comment by MemeHoovy** [comment]
> > > > > I Will Use Some From PE And The Original
> > > > 
> > > > 
> > > > your discord don't work
> > > 
> > > 
> > > My Discord?
> > 
> > 
> > ye, the username don't work
> 
> Oh. I Just Changed The My Username

yeah, so the old one don't work

**Comment by LilDrippyMyFnf** [comment]
https://discord.gg/ttwTJTFu go here

**Comment by LilDrippyMyFnf** [comment]
> https://discord.gg/ttwTJTFu go here

go to my server so we can chat about stuff

**Comment by MemeHoovy** [comment]
> > https://discord.gg/ttwTJTFu go here
> 
> go to my server so we can chat about stuff

cool, but I wasn't refering to you though

**Comment by LilDrippyMyFnf** [comment]
ok
