### ISSUE TITLE
Android port not working 

### ISSUE THREAD

**Issue by MMbay64** [LilDrippyMyFnf/FNF-BitEnigne#53]
![Screenshot_20221028-194131](https://user-images.githubusercontent.com/115948389/198751035-ef129384-a81d-4735-a02e-69b7ae19a73f.png)

So I was downloading the 0.3.0 Android port,and Thiers NO thing we're I can play it 
So if anyone can fix and help me on this,I'll gladly take feedback on this

**Comment by LilDrippyMyFnf** [comment]
hmmm.... thats a pretty good idea i should fix
