### ISSUE TITLE
Mobile port still broken and 0.3.2 is soon

### ISSUE THREAD

**Issue by MMbay64** [LilDrippyMyFnf/FNF-BitEnigne#65]
MOBLIE PORTTT

**Comment by LilDrippyMyFnf** [comment]
tf?

**Comment by LilDrippyMyFnf** [comment]
just give us time

**Comment by MMbay64** [comment]
Still

**Comment by LilDrippyMyFnf** [comment]
> Still

NOTHING YOU DUMBASSS

**Comment by LilDrippyMyFnf** [comment]
were not gonna work on moblie port if you don't stfu about it

HOW BOUT YOU DO IT SINCE YOU KEEP REMINDING US

**Comment by MMbay64** [comment]
> were not gonna work on moblie port if you don't stfu about it
> 
> HOW BOUT YOU DO IT SINCE YOU KEEP REMINDING US

Idk how to code this in MOBLIE

**Comment by LilDrippyMyFnf** [comment]
> > were not gonna work on moblie port if you don't stfu about it
> > HOW BOUT YOU DO IT SINCE YOU KEEP REMINDING US
> 
> Idk how to code this in MOBLIE

SO GIVE US TIMEMEMEMMEMEME

**Comment by MMbay64** [comment]
No

**Comment by LilDrippyMyFnf** [comment]
> No

your being banned

**Comment by MMbay64** [comment]
> > No
> 
> your being banned

Dudes just explainih his family

**Comment by LilDrippyMyFnf** [comment]
> > > No
> > 
> > 
> > your being banned
> 
> Dudes just explainih his family

my bro's begging cuz he on a iphone 3
