### ISSUE TITLE
Week 7 please 

### ISSUE THREAD

**Issue by MMbay64** [LilDrippyMyFnf/FNF-BitEnigne#68]
**Describe the bug**
There is no week 7 

**Expected behavior**
ADD WEEK 7

**Comment by BushTrain460615** [comment]
they added me as a collaborator so, I could add it

**Comment by MMbay64** [comment]
> they added me as a collaborator so, I could add it

No

**Comment by MMbay64** [comment]
> > they added me as a collaborator so, I could add it
> 
> No

They added you cuz your a great coder
