### ISSUE TITLE
Bit Engine Ending in 1 hour

### ISSUE THREAD

**Issue by LilDrippyMyFnf** [LilDrippyMyFnf/FNF-BitEnigne#73]
yeah,it'll be archived for awhile and might be deleted

**Comment by DomZ560** [comment]
Nooooooo

**Comment by DomZ560** [comment]
1 hour?1??

**Comment by LilDrippyMyFnf** [comment]
> 1 hour?1??

yeah,its old at this point,so basically its done forrrr

**Comment by DomZ560** [comment]
> > 1 hour?1??
> 
> yeah,its old at this point,so basically its done forrrr

((((
